### ISSUE TITLE
DBOS-SDK Windows quickstart needs an update

### ISSUE THREAD

**Issue by manojdbos** [dbos-inc/dbos-docs#85]
command line requires nvm be installed before installing Node.js .
Reported by parv

**Comment by chuck-dbos** [comment]
Another thing reported about Windows quickstart is that it refers to `export` to set environment variables; Windows uses `set`.  Actually, there are a lot of ways to succeed with Windows, depending if it is CMD.exe, PowerShell, bash (which you can get with git, or other places), or WSL.  Some of those use `set`.

**Comment by jtcoyle** [comment]
I just proposed a pulled request that I created for the Quick Start guide.  I have been able to replicate this on Windows 10 and 11 multiple times.  I hope this helps.
